services:
  postgres:
    container_name: metamentor-postgres
    image: postgres
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    ports:
      - 1206:5432
    volumes:
      - metamentor:/var/lib/postgresql/data/

volumes:
  metamentor: